#!/usr/bin/env python3
"""T7 IRAM corpus builder: budget-mismatch negative + IRAM contract gate.

Starting from the gate-approved iram_probe.elf (check_plugin_elf.cmake ran
on it, including the .plugin_iram section gates; the positive iram_probe.mpb
itself comes from the poca_plugin pipeline), this script:

  1. verifies the IRAM section contract that the section-table gates cannot
     see: the disassembly of .plugin_iram must contain no l32r literal load.
     An l32r executed from the IRAM window would fetch its literal from the
     PSRAM text window, beyond the 256 KB backward-only l32r reach - a
     runtime-only fault, so it is rejected here, at build time;
  2. builds the negative container iram_mismatch: same ELF, manifest
     declares iram_required_bytes = section size + 16. This must go through
     assemble_mpb (the hostile_signed pattern proven in T5/T6) because
     build_mpb itself refuses a declared value that disagrees with the
     extracted section size. The device-side rejection must then come from
     loader patch p5, before any allocation and before any plugin byte
     executes (PLUG-009 / MEM 4.2.4 budget consistency).
"""

from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[5]
sys.path.insert(0, str(REPO_ROOT / "tools"))

from frame_tools.manifest_builder import (  # noqa: E402
    PAYLOAD_TYPE_ELF,
    Manifest,
    Payload,
    assemble_mpb,
    derive_key_id,
    load_private_key,
)

MISMATCH_DELTA = 16
MAX_MEMORY_BYTES = 262144


def check_iram_contract(elf_path: Path, objdump: str) -> int:
    """Assert .plugin_iram exists, has no l32r, no split subsections.

    Returns the section size."""
    sections = subprocess.run(
        [objdump, "-h", str(elf_path)], check=True, capture_output=True, text=True
    ).stdout
    iram_rows = [line for line in sections.splitlines() if re.search(r"\s\.plugin_iram\s", line)]
    extras = [line for line in sections.splitlines() if re.search(r"\s\.plugin_iram\.\S+\s", line)]
    if extras:
        names = " ".join(re.search(r"(\S*\.plugin_iram\.\S*)\s", line).group(1) for line in extras)
        raise SystemExit(
            f"[iram-corpus] FAIL iram_probe: split IRAM subsections present: {names} "
            "(literal pools must not leak out of .plugin_iram)"
        )
    if not iram_rows:
        raise SystemExit("[iram-corpus] FAIL iram_probe: no .plugin_iram section in image")

    disasm = subprocess.run(
        [objdump, "-d", "-j", ".plugin_iram", str(elf_path)],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    literals = [line.strip() for line in disasm.splitlines() if re.search(r"\bl32r\b", line)]
    if literals:
        raise SystemExit(
            "[iram-corpus] FAIL iram_probe: l32r literal load inside .plugin_iram "
            f"(unreachable across the IRAM/PSRAM window split): {'; '.join(literals)}"
        )

    size = int(iram_rows[0].split()[2], 16)
    print(f"[iram-corpus] iram contract OK: .plugin_iram size={size} l32r=0 subsections=0")
    return size


def write_meta(out_dir: Path, name: str, container: bytes) -> None:
    digest = hashlib.sha256(container).hexdigest()
    upper = name.upper()
    generated_by = "poc/apps/poc_a/plugins/iram_probe/build_iram_corpus.py"
    header = (
        f"/* Generated by {generated_by} - do not edit. */\n"
        f"#define POCA_{upper}_MPB_SIZE {len(container)}u\n"
        f'#define POCA_{upper}_MPB_SHA256 "{digest}"\n'
        f'#define POCA_{upper}_NAME "{name}"\n'
        f'#define POCA_{upper}_VERSION "1.0.0"\n'
        f'#define POCA_{upper}_ENTRY "frame_plugin_entry"\n'
    )
    (out_dir / "generated" / f"poca_{name}_meta.h").write_text(header)
    print(f"[iram-corpus] {name}.mpb size={len(container)} sha256={digest}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--probe-elf", required=True)
    parser.add_argument("--objdump", required=True)
    parser.add_argument("--key", required=True)
    parser.add_argument("--out-dir", required=True)
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    (out_dir / "generated").mkdir(parents=True, exist_ok=True)
    key = load_private_key(Path(args.key))
    elf = Path(args.probe_elf).read_bytes()

    section_size = check_iram_contract(Path(args.probe_elf), args.objdump)

    mismatch = Manifest("iram_mismatch", "1.0.0")
    mismatch.set("max_memory_bytes", MAX_MEMORY_BYTES)
    mismatch.set("iram_required_bytes", section_size + MISMATCH_DELTA)
    negative = assemble_mpb(
        manifest_bytes=mismatch.encode(),
        payloads=[Payload(kind=PAYLOAD_TYPE_ELF, data=elf)],
        key_id=derive_key_id(key.public_key()),
        flags=0,
        security_epoch=1,
        signing_key=key,
    )
    (out_dir / "iram_mismatch.mpb").write_bytes(negative)
    write_meta(out_dir, "iram_mismatch", negative)
    print(
        f"[iram-corpus] iram_mismatch declares iram_required_bytes="
        f"{section_size}+{MISMATCH_DELTA} (loader p5 must reject pre-allocate)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
