#!/usr/bin/env python3
"""Hostile-path packaging for the T6 C++ feature-rejection corpus.

The probe ELFs are built by poca_cxx_probe() and are NEVER gate-approved
(the expected-failure runner proves check_plugin_elf.cmake rejects each
one); packaging them here therefore mirrors the T5 hostile_signed pattern:
the containers are structurally valid, signed with the TEST-only key and
carry a genuine xtensa ELF payload, so mpb verification passes on device
and the rejection must come from the loader layers (patch p1 relocation
allowlist, patch p4 forbidden-section policy).

  cxx_ctor        v1 probe ELF as built (.ctors present)
                  -> p4 must reject with -EINVAL pre-execute
  cxx_tls         v3 probe ELF as built (.tdata/.tbss + R_XTENSA_TLSDESC_*)
                  -> p4 (sections) must reject with -EINVAL pre-execute
  neg_tls_nosect  v3 bytes with the .tdata/.tbss section names renamed
                  (same-length ".xdata"/".xbss" overwrite inside .shstrtab)
                  -> p4 finds nothing; p1 must reject the R_XTENSA_TLSDESC_*
                  relocation types with -EINVAL. This row isolates the
                  relocation-layer rejection from the section-layer one.
"""

from __future__ import annotations

import argparse
import hashlib
import struct
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[5]
sys.path.insert(0, str(REPO_ROOT / "tools"))

from frame_tools.manifest_builder import (  # noqa: E402
    PAYLOAD_TYPE_ELF,
    Manifest,
    Payload,
    build_mpb,
    load_private_key,
)

MAX_MEMORY_BYTES = 262144
SHT_STRTAB = 3


def shstrtab_span(elf: bytes) -> tuple[int, int]:
    (shoff,) = struct.unpack_from("<I", elf, 32)
    (shentsize,) = struct.unpack_from("<H", elf, 46)
    (shstrndx,) = struct.unpack_from("<H", elf, 50)
    shdr = struct.unpack_from("<10I", elf, shoff + shstrndx * shentsize)
    if shdr[1] != SHT_STRTAB:
        raise SystemExit("e_shstrndx does not name a SHT_STRTAB; cannot patch")
    return shdr[4], shdr[4] + shdr[5]


def rename_section(elf: bytes, old: str, new: str) -> bytes:
    if len(old) != len(new):
        raise SystemExit(f"rename must be same-length: {old} -> {new}")
    start, end = shstrtab_span(elf)
    table = elf[start:end]
    needle = old.encode() + b"\x00"
    count = table.count(needle)
    if count != 1:
        raise SystemExit(f"expected exactly one '{old}' in .shstrtab, found {count}")
    buf = bytearray(elf)
    offset = start + table.index(needle)
    buf[offset : offset + len(new)] = new.encode()
    print(f"  .shstrtab@0x{offset:04x}: '{old}' -> '{new}'")
    return bytes(buf)


def package(out_dir: Path, name: str, elf: bytes, key) -> None:
    manifest = Manifest(name, "1.0.0")
    manifest.set("max_memory_bytes", MAX_MEMORY_BYTES)
    container = build_mpb(
        manifest,
        [Payload(kind=PAYLOAD_TYPE_ELF, data=elf)],
        signing_key=key,
        security_epoch=1,
    )
    (out_dir / f"{name}.mpb").write_bytes(container)
    digest = hashlib.sha256(container).hexdigest()
    upper = name.upper()
    header = (
        f"/* Generated by poc/apps/poc_a/plugins/cxx_probes/build_cxx_probes.py - do not edit. */\n"
        f"#define POCA_{upper}_MPB_SIZE {len(container)}u\n"
        f"#define POCA_{upper}_MPB_SHA256 \"{digest}\"\n"
        f"#define POCA_{upper}_NAME \"{name}\"\n"
        f"#define POCA_{upper}_VERSION \"1.0.0\"\n"
        f"#define POCA_{upper}_ENTRY \"frame_plugin_entry\"\n"
    )
    (out_dir / "generated" / f"poca_{name}_meta.h").write_text(header)
    elf_digest = hashlib.sha256(elf).hexdigest()
    print(f"[cxx-corpus] {name}.mpb size={len(container)} sha256={digest} "
          f"(elf sha256={elf_digest})")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ctor-elf", required=True)
    parser.add_argument("--tls-elf", required=True)
    parser.add_argument("--key", required=True)
    parser.add_argument("--out-dir", required=True)
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    (out_dir / "generated").mkdir(parents=True, exist_ok=True)
    key = load_private_key(Path(args.key))

    ctor_elf = Path(args.ctor_elf).read_bytes()
    tls_elf = Path(args.tls_elf).read_bytes()

    print("[cxx-corpus] cxx_ctor (probe ELF, .ctors present)")
    package(out_dir, "cxx_ctor", ctor_elf, key)
    print("[cxx-corpus] cxx_tls (probe ELF, .tdata/.tbss + TLSDESC relocs)")
    package(out_dir, "cxx_tls", tls_elf, key)
    print("[cxx-corpus] neg_tls_nosect (TLS sections renamed; p1-only row)")
    renamed = rename_section(tls_elf, ".tdata", ".xdata")
    renamed = rename_section(renamed, ".tbss", ".xbss")
    package(out_dir, "neg_tls_nosect", renamed, key)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
