#!/usr/bin/env python3
"""T8 admission corpus builder: over-declared max_memory_bytes negative.

Starting from the gate-approved baseline.elf (check_plugin_elf.cmake ran on
it), builds the negative container neg_maxmem: the manifest declares
max_memory_bytes = 614400 (600 KiB), past the 512 KiB hard maximum of
MEM-003/PLUG-004 admission. Manifest.encode() would refuse the value
(cross-field validation rejects > MAX_PLUGIN_MEMORY_BYTES), so the manifest
TLVs are hand-packed here and the container goes through assemble_mpb (the
hostile_signed pattern proven in T5/T6/T7). The signature is valid: the
on-device rejection must come from the poca admission check
(max_memory_bytes > 512 KiB hard max), before esp_elf_init and before any
plugin byte executes.
"""

from __future__ import annotations

import argparse
import hashlib
import struct
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[5]
sys.path.insert(0, str(REPO_ROOT / "tools"))

from frame_tools.manifest_builder import (  # noqa: E402
    PAYLOAD_TYPE_ELF,
    PAYLOAD_ENTRY_SIZE,
    SIGNATURE_RECORD_SIZE,
    TLV_FLAG_REQUIRED,
    TLV_HEADER_FMT,
    Payload,
    assemble_mpb,
    derive_key_id,
    load_private_key,
    sign_digest_deterministic,
)

DECLARED_MAX_MEMORY = 600 * 1024
HARD_MAX = 512 * 1024


def _tlv(field_id: int, flags: int, value: bytes) -> bytes:
    return struct.pack(TLV_HEADER_FMT, field_id, flags, len(value)) + value


def hostile_manifest_bytes() -> bytes:
    """Hand-packed manifest TLVs (name=1, version=2, max_memory_bytes=4)."""
    return b"".join(
        [
            _tlv(1, TLV_FLAG_REQUIRED, b"baseline"),
            _tlv(2, TLV_FLAG_REQUIRED, b"1.0.0"),
            _tlv(4, 0, struct.pack("<I", DECLARED_MAX_MEMORY)),
        ]
    )


def hostile_signed(manifest_bytes: bytes, elf: bytes, key) -> bytes:
    """Sign over arbitrary manifest bytes (the T2/T3 tests/test_manifest_builder
    hostile_signed pattern): assemble_mpb would run its post-sign semantic
    self-verify, which refuses max_memory_bytes > 512 KiB — exactly the rule
    this fixture violates — so the digest is signed directly and the IEEE
    P1363 r||s record is spliced in at signature_offset."""
    container = assemble_mpb(
        manifest_bytes=manifest_bytes,
        payloads=[Payload(kind=PAYLOAD_TYPE_ELF, data=elf)],
        key_id=derive_key_id(key.public_key()),
        flags=0,
    )
    table_end = struct.unpack_from("<I", container, 52)[0] + PAYLOAD_ENTRY_SIZE
    digest = hashlib.sha256(container[:table_end]).digest()
    signature = sign_digest_deterministic(key, digest)
    offset = struct.unpack_from("<I", container, 60)[0]
    container = bytearray(container)
    container[offset + 8 : offset + SIGNATURE_RECORD_SIZE] = signature
    return bytes(container)


def write_meta(out_dir: Path, name: str, container: bytes) -> None:
    digest = hashlib.sha256(container).hexdigest()
    upper = name.upper()
    header = (
        f"/* Generated by poc/apps/poc_a/plugins/coexist/build_maxmem_corpus.py - do not edit. */\n"
        f"#define POCA_{upper}_MPB_SIZE {len(container)}u\n"
        f'#define POCA_{upper}_MPB_SHA256 "{digest}"\n'
        f'#define POCA_{upper}_NAME "baseline"\n'
        f'#define POCA_{upper}_VERSION "1.0.0"\n'
        f'#define POCA_{upper}_ENTRY "frame_plugin_entry"\n'
    )
    (out_dir / "generated" / f"poca_{name}_meta.h").write_text(header)
    print(f"[maxmem-corpus] {name}.mpb size={len(container)} sha256={digest}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--baseline-elf", required=True)
    parser.add_argument("--key", required=True)
    parser.add_argument("--out-dir", required=True)
    args = parser.parse_args()

    if DECLARED_MAX_MEMORY <= HARD_MAX:
        raise SystemExit("[maxmem-corpus] fixture bug: declared value must exceed the hard max")

    out_dir = Path(args.out_dir)
    (out_dir / "generated").mkdir(parents=True, exist_ok=True)
    key = load_private_key(Path(args.key))
    elf = Path(args.baseline_elf).read_bytes()

    container = hostile_signed(hostile_manifest_bytes(), elf, key)
    (out_dir / "neg_maxmem.mpb").write_bytes(container)
    write_meta(out_dir, "neg_maxmem", container)
    print(
        f"[maxmem-corpus] neg_maxmem declares max_memory_bytes={DECLARED_MAX_MEMORY} "
        f"(admission must reject pre-init: > {HARD_MAX} hard max)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
